### ISSUE TITLE
Bugreport: klog total gives wrong values

### ISSUE THREAD

**Issue by wAuner** [jotaen/klog#14]
I created an entry from a template with `klog append` but today it does not seem to work:

The entry created looks like this:
```
2021-02-11 (8h!)
Wooooork!
   6:56 - ?
```
When I now run `klog total --today` (with or without the diff flag) it always says the total is 0m.
This could be a parsing error in `klog total`

**Comment by wAuner** [comment]
ok seems I have misunderstood the behavior. I noticed now that only `--live` includes the open range. 
Just remembered that we talked about that yesterday, I just forgot....Sorry

**Comment by jotaen** [comment]
It’s good that you bring this up anyway, because I think the tool should be more transparent and predictable in that regard. I have that on my todo list already. E.g. in your example the output could read `(In 4 records, excluding 1 open time range)` or something like that. Same if you have an open range that is not dated today or yesterday: this should really cause a warning, because you most likely forgot to close it.

**Comment by jotaen** [comment]
There now is also `klog total --now` and `klog report --now` to have the “now” magic for those as well. (In addition and equivalently to the standalone `klog now`).
