### ISSUE TITLE
I'm confused by time

### ISSUE THREAD

**Issue by xp12047** [jotaen/klog#213]
help, see  
The plan I started last night stopped this morning  
I tried several times to no avail   
![mmexport1663736191191](https://user-images.githubusercontent.com/56335408/191417647-8a28d823-c7aa-453b-a60c-c82adbff3e6e.png)
![mmexport1663736193479](https://user-images.githubusercontent.com/56335408/191417652-b71aa556-e912-4c0c-9c84-cb2c02cc8884.png)
![mmexport1663736196917](https://user-images.githubusercontent.com/56335408/191417653-83b54add-d360-4864-823e-f9a98b596bcd.png)
![mmexport1663736201602](https://user-images.githubusercontent.com/56335408/191417657-ec3e1167-4634-45c2-98bb-86c7aac816c7.png)   
At the beginning.  I can't directly 22:36-9:00   
Help give pointers, thank you

**Comment by vladdeSV** [comment]
The `<` and `>` means the previous / upcoming day.

```
2022-09-21
  09:00 - 10:00>   this translates to "9am the 21st of September" to "10am the 22nd of September"
```

This is why you get the "Entry in the future", because it ends on the 22nd of September, while it's still the 21st.

---

Looking at your example, if you want to add an entry for the 21st of September that started at 22:36 the day before, you could do:

```
2022-09-20
  <22:36 - 9:00
```

Finally, just to hammer down that you do not need either `<` nor `>`:

```
2022-09-21
  9:00 - 10:00   this is 1 hour total
```

**Comment by xp12047** [comment]
> 和表示前一天`<`/`>`即将到来的一天。
> 
> ```
> 2022-09-21
>   09:00 - 10:00>   this translates to "9am the 21st of September" to "10am the 22nd of September"
> ```
> 
> 这就是为什么您会获得“未来条目”的原因，因为它在 9 月 22 日结束，而现在仍然是 21 日。
> 
> 看看你的例子，如果你想为前一天 22:36 开始的 9 月 21 日添加一个条目，你可以这样做：
> 
> ```
> 2022-09-20
>   <22:36 - 9:00
> ```
> 
> 最后，只是为了确定您不需要也不`<`需要`>`：
> 
> ```
> 2022-09-21
>   9:00 - 10:00   this is 1 hour total
> ```

thanks😁
