### ISSUE TITLE
Systray widget should display time in menubar

### ISSUE THREAD

**Issue by tecunningham** [jotaen/klog#28]
It'd be great if the MacOS systray widget displayed today's cumulative time in the menubar.

Could have an option to display all time, or just for a specific tag.

**Comment by vladdeSV** [comment]
A few suggestions for what should be displayed:

- if an open-ended range is present, it should be visualized somehow, eg. `2h40m...`
- if there is a should-total, that should (optionally) be visible, eg. `6h20m / 8h`

There are most likely better ways to visualize these.

(I do not own a mac, so I can only comment on the functionality per se)

**Comment by jotaen** [comment]
Ultimately, it would be cool if one could configure the display string with placeholders. Will think about it!

**Comment by vladdeSV** [comment]
Speaking of placeholders, the mac app [Day-O](https://shauninman.com/archive/2020/04/08/day_o_mac_menu_bar_clock_for_catalina) has a nice placeholder feature. Although it it geared towards dates, something similar for *klog* might be interesting.

I was very happy with they way I could configure the displayed text. It is [very customizable](https://github.com/vladdeSV/my-mac#day-o).

**Comment by jotaen** [comment]
I’m currently considering to discontinue the widget, at least in the way it’s currently implemented:

- I don’t think a lot of people are actually using it, including myself.
- I’ve been using a [3rd-party library](https://github.com/caseymrm/menuet) for the native UI, but that looks abandoned now. It uses deprecated Apple APIs, and it doesn’t compile on modern M1 / ARM Macs anymore.
- The current approach to bundle the UI into the CLI executable is very limited, and it’s hard to add more powerful features. I can’t even add the klog icon, because that would require me to ship a proper application bundle instead of just a binary.

Overall I think the embedded widget is a dead end. For now, I don’t mind keeping the code as it is, but I probably won’t extend it anymore, or invest time into porting it to ARM. I still believe a native widget would be terrific, but then it should be more powerful and fun to use (e.g. a graphical panel), in which case it makes more sense to have a standalone application.
