### ISSUE TITLE
Raise warning about overlapping time ranges

### ISSUE THREAD

**Issue by vladdeSV** [jotaen/klog#61]
Currently overlapping times are allowed, with the specification mentioning nothing about overlapping time ranges. The following is legal according to the specification and `klog`:

```klog
2021-04-20
    00:00 - 01:00 foo
    00:00 - 01:00 bar
```

This intuitively feels as if an error has been made when manually entering times.

I believe overlapping time ranges' legality should be clarified, whether that would be an error, a warning, or perfectly legal.

---

*Side note*: I am unsure if this is the appropriate issue to bring this up, but with overlapping time ranges I can log more than 24 hours for a date. The same is true for time durations, where you can log `9999h` for a day.

Personally, I am unsure where I, myself, would draw the line. If overlapping times should be illegal, I also believe that a maximum of 24 hours would be allowed to be logged per date (disregarding summertime). If it is legal, then I believe there should be no maximum cap for time logged per date.

**Comment by jotaen** [comment]
I was on the fence about this topic, but then decided to not complain about these things, because I thought there might be legitimate use-cases. E.g. if you want to take over 25h of overtime from the previous month/file. My reasoning was also inline with yours that the error handling should be consistent, so it would be strange to reject certain things but then not complain about others.

I haven’t considered the warnings actually, maybe because I only added them later. I think it’s a good idea to raise a warning for both overlapping time ranges and >24h total durations. That feels unobstrusive and you can always silence it with `--no-warn`.

Btw.: there is an [FAQ entry](https://klog.jotaen.net/#faq) regarding this in the docs. I initially thought that the spec is not the right place for this, but now that I think about it more it might be worth to add another section to the spec to clarify these “practical” topics. I opened a separate ticket for this: https://github.com/jotaen/klog/issues/63
